services:
  tts:
    build:
      context: .
      dockerfile: Dockerfile
    image: sherpa-tts:dev
    container_name: sherpa-tts-dev
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - ./logs:/logs
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
